### ISSUE TITLE
XSS vulnerability in comments

### ISSUE THREAD

**Issue by golgote** [xzilla/phppgadmin#9]
Comments on Tables and Schemas, and maybe other objects, are not HTML escaped so it is possible to inject HTML in them, which is a XSS vulnerability.
For example:
```
COMMENT ON SCHEMA public IS '<b>this is bold</b>';
```
will output "this is bold" in bold...

PS: You should allow posting issues on the main phppgadmin repository in Github.
Thank you.

**Comment by xzilla** [comment]
I believe this is fixed upstream, if you can find examples on the main phppgadmin repo git master, please lmk. 

wrt issues, yes, i didn't realize how messed up this is. at the moment, people are supposed to use the sourceforge list tracker, but clearly that isn't happening. I do plan to clean that up sooner rather than later.
